CREATE TABLE restaurants (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug       VARCHAR(255) NOT NULL UNIQUE,
    name       VARCHAR(255) NOT NULL,
    category   VARCHAR(255) NOT NULL
);

CREATE TABLE restaurant_locations (
    id            UUID PRIMARY KEY,
    restaurant_id BIGINT NOT NULL REFERENCES restaurants (id),
    latitude      NUMERIC(5, 2) NOT NULL,
    longitude     NUMERIC(5, 2) NOT NULL,
    address       TEXT NOT NULL
);

CREATE INDEX idx_restaurant_locations_restaurant_id ON restaurant_locations (restaurant_id);

CREATE TABLE menu_items (
    id            UUID PRIMARY KEY,
    restaurant_id BIGINT NOT NULL REFERENCES restaurants (id),
    name          VARCHAR(255) NOT NULL,
    menu_category VARCHAR(255),
    serving_size  VARCHAR(255),
    calories      INTEGER,
    protein       NUMERIC(5, 2),
    carbs         NUMERIC(5, 2),
    fat           NUMERIC(5, 2),
    allergens     TEXT,
    source        VARCHAR(255),
    last_verified DATE
);

CREATE INDEX idx_menu_items_restaurant_id ON menu_items (restaurant_id);
